# edit port mapping if conflicts
# -ports:
# host-port: container-port

version: "3.3"
services:
  cli:
    build: .
    # command: crond -f -l 8
    volumes:
      - ../:/workspaces/laravel
      # - C:\Users\GANI\.ssh:/home/user/.ssh
      # - ./ssh:/home/user/.ssh
      #- ./cli/cron:/etc/periodic/1min
      # - ./cli/test.txt:/test.txt
    dns:
      - 1.1.1.1 # dns server 1

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example456
      MYSQL_DATABASE: laravel-app
    # uncomment this block if needed db admin
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080

    # redis:
    #   image: redis:6.2-alpine

    # queue:
    #   build: supervisor
    #   image: supervisor
    #   volumes:
    #     - ..:/workspaces/laravel
    # Switch to "webuser" before running `php artisan`
    # Declare command in list manner for environment variable expansion
    # command: ["cd /workspaces/laravel/partnered && php artisan queue:work --tries=3"]
